services:
  - type: web
    name: ayo-2-joj-dakar
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false   # tu la saisiras manuellement dans le dashboard Render
